#!/bin/bash


wlblazers_process=`ps -ef|grep wlblazers.py |grep -v grep|wc -l`
if [ $wlblazers_process -le "3" ];then
       echo "`date` wlblazers server is not run."
else
       echo "`date` wlblazers server is running..."
fi
