#!/bin/bash

#check basedir
#############################################################################
if test -z "$basedir"
then
  basedir=/usr/local/wlb/python
else
  basedir="$basedir"
fi

arg=$1
wlblazers_process=`ps -ef|grep wlblazers.py |grep -v grep|wc -l`
case "$arg" in
  'status')
    #check wlblazers status
    if [ $wlblazers_process -ge "2" ];then
       echo "wlblazers server is running..."
    else
       echo "wlblazers server is not run!"
    fi
  ;;

  'start')
    #start wlblazers
    if [ $wlblazers_process -ge "2" ];then
       echo " wlblazers server is already run!"
    else
       cd $basedir 
       if [ -f "wlblazers.py" ]; then
          nohup python wlblazers.py &> logs/wlblazers.log & 
       else
          nohup python wlblazers.pyc &> logs/wlblazers.log & 
       fi


       sleep 5
       
       wlblazers_process=`ps -ef|grep wlblazers.py |grep -v grep|wc -l`
       if [ $wlblazers_process -ge "2" ];then
          echo "wlblazers server start success!"
       else
          echo "wlblazers server start fail!"
       fi
    fi
  ;;

  'stop')
    #stop wlblazers
    if [ $wlblazers_process -le "2" ];then
       echo "wlblazers server is not running!"
    else
       #killall python wlblazers.py*
       ps -ef | grep "check_mysql.py" | grep -v -E "vi|grep" | awk '{print $2}' |while read line; do kill -9 $line; echo "wlblazers processes id $line been stop"; done 
       ps -ef | grep "check_oracle.py" | grep -v -E "vi|grep" | awk '{print $2}' |while read line; do kill -9 $line; echo "wlblazers processes id $line been stop"; done 
       ps -ef | grep "check_sqlserver.py" | grep -v -E "vi|grep" | awk '{print $2}' |while read line; do kill -9 $line; echo "wlblazers processes id $line been stop"; done 
       ps -ef | grep "check_os.py" | grep -v -E "vi|grep" | awk '{print $2}' |while read line; do kill -9 $line; echo "wlblazers processes id $line been stop"; done 
       ps -ef | grep "alert_main.py" | grep -v -E "vi|grep" | awk '{print $2}' |while read line; do kill -9 $line; echo "wlblazers processes id $line been stop"; done 
       ps -ef | grep "clean_history.py" | grep -v -E "vi|grep" | awk '{print $2}' |while read line; do kill -9 $line; echo "wlblazers processes id $line been stop"; done 
       ps -ef | grep "wlblazers.py" | grep -v -E "vi|grep" | awk '{print $2}' |while read line; do kill -9 $line; echo "wlblazers processes id $line been stop"; done 
    fi
  ;;

  '--help')
    #for help
    echo "wlblazers help:"
    echo "support-site:  www.wlblazers.com"
    echo "===================================================================="
    echo "start        Start wlblazers monitor server; Command: #wlblazers start"
    echo "stop         Stop wlblazers monitor server; Command: #wlblazers stop"
    echo "status       Check wlblazers monitor run status; Command: #wlblazers status"
  ;;
    *)
        echo "Please input  --help to read the help info."
    ;;

esac

exit 0  
  



